### ISSUE TITLE
Document front end coding standards for `.ts` vs `.d.ts`

### ISSUE THREAD

**Issue by seancolsen** [centerofci/mathesar-wiki#24]
I still find this practice weird and I don't fully understand the rationale. If it were me, I'd just use `.ts`  all the time and never `.d.ts`. We should document this practice and a standard and explain the rationale.

**Comment by seancolsen** [comment]
@pavish Would you be up for writing this documentation?

**Comment by pavish** [comment]
@seancolsen Yes, I'll come up with the content.

**Comment by seancolsen** [comment]
In https://github.com/centerofci/mathesar/issues/1135 we decided to discontinue using `*.d.ts` files, so I'm closing this ticket now.
