### ISSUE TITLE
Add information about lexical Precedence to Filter spec documentation

### ISSUE THREAD

**Issue by silentninja** [centerofci/mathesar-wiki#32]
## Problem

Filters as of now don't have support for nesting and are flat, so confusion can arise if multiple logical operators are used on the same level.

## Proposed Solution

We would need to mention the [precedence order of the operators](https://www.postgresql.org/docs/7.2/sql-precedence.html) to specify why certain operators took priority over the other.

## Additional Context

This issue came out of a [matrix discussion](https://matrix.to/#/!xInuTkBwjXZXYatIlm:matrix.mathesar.org/$LiXXEjK0Y8vtezHdIvHTa1xVHImkLkO1pyRASplTxRM?via=matrix.mathesar.org&via=matrix.org)

**Comment by dmos62** [comment]
Notably, this goes against the [filters product concept page](https://wiki.mathesar.org/en/product/concepts/filters) where it says:

> The order than you apply filters in does not matter. Since filters only look at the data in a single row, you can apply them in any order and end up with the same result.

**Comment by silentninja** [comment]
> The order than you apply filters in does not matter. Since filters only look at the data in a single row, you can apply them in any order and end up with the same result.

I think it is pointing to the filter condition(id = 1) and not the operator that joins them. Based on what @pavish has commented on the [matrix](https://matrix.to/#/!xInuTkBwjXZXYatIlm:matrix.mathesar.org/$xssfbP5AYpuSEkWM7oqK8oTn7E4dqoJZwo7NJzsppYY?via=matrix.mathesar.org&via=matrix.org) there can be only one joining operator for the whole filter set

**Comment by kgodey** [comment]
> I think it is pointing to the filter condition(id = 1) and not the operator that joins them. Based on what @pavish has commented on the [matrix](https://matrix.to/#/!xInuTkBwjXZXYatIlm:matrix.mathesar.org/$xssfbP5AYpuSEkWM7oqK8oTn7E4dqoJZwo7NJzsppYY?via=matrix.mathesar.org&via=matrix.org) there can be only one joining operator for the whole filter set

Yes, this is correct. What I meant was that if you have the same filters with the same operators applied, the order doesn't matter, i.e. filters are [commutative](https://en.wikipedia.org/wiki/Commutative_property). 

---

@silentninja Where is the filter spec documentation that needs to be updated for this issue?

**Comment by kgodey** [comment]
I wrote up an architecture wiki page for [filters](https://wiki.mathesar.org/en/engineering/architecture/filters), let's keep this updated. I haven't added anything about lexical precedence yet.

**Comment by pavish** [comment]
If the filter API supports nested filters (which was decided) in a similar format to sqlalchemy-filters, we wouldn't have a scenario with multiple operators.

Do we need to document lexical precedence?

**Comment by kgodey** [comment]
> Do we need to document lexical precedence?

I don't think so. I'll close this issue for now, we can reopen if needed.
