### ISSUE TITLE
Style wiki using our brand colors

### ISSUE THREAD

**Issue by kgodey** [centerofci/mathesar-wiki#81]

**Comment by kgodey** [comment]
@ghislaineguerin We should just do whatever we can using CSS overwrites. Custom theming is not fully supported unless we compile our own version of Wiki.js ([see docs here](https://docs.requarks.io/dev/themes)), and I don't think that effort is worth it right now.

**Comment by ghislaineguerin** [comment]
@kgodey please verify the color replacement here: https://wiki.mathesar.org/en/home

**Comment by kgodey** [comment]
Looks great @ghislaineguerin!
