### ISSUE TITLE
Typo in the word `links`

### ISSUE THREAD

**Issue by Aritra8438** [centerofci/mathesar-wiki#97]
I noticed a small typo in the word `links`. It's written as `linka`.

Notice the paragraph in sky-blue background.

<img width="960" alt="image" src="https://github.com/centerofci/mathesar-wiki/assets/64671908/151243dd-d680-415a-b126-bc919cf59e91">

**Comment by kgodey** [comment]
Thanks @Aritra8438! For small issues like this, you can just submit a PR directly, no need to make an issue.
